# Generated by Django 3.2.8 on 2021-10-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='expiry_date',
        ),
    ]
