# Generated by Django 3.2.8 on 2021-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_auto_20211005_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='current_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='expiry_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
