# Generated by Django 3.2.8 on 2021-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_auto_20211005_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
