# Generated by Django 3.2.8 on 2021-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_issuebook_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
