# Generated by Django 3.2.8 on 2021-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_alter_issuebook_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='date',
            new_name='current_date',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
