# Generated by Django 3.2.8 on 2021-10-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0010_auto_20211005_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnbook',
            old_name='bookid3',
            new_name='issuebook_id',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='bookid1',
        ),
    ]
