# Generated by Django 3.2.8 on 2021-10-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0011_auto_20211005_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='issuebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuebook_id', to='libraryApp.issuebook'),
        ),
    ]
