# Generated by Django 3.2.8 on 2021-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0012_alter_returnbook_issuebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='availiblity',
            field=models.BooleanField(default=False),
        ),
    ]
