# Generated by Django 3.2.8 on 2021-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0013_issuebook_availiblity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='availiblity',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='availiblity',
            field=models.BooleanField(default=False),
        ),
    ]
