# Generated by Django 3.2.8 on 2021-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0014_auto_20211006_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='availiblity',
            field=models.BooleanField(),
        ),
    ]
