# Generated by Django 3.2.8 on 2021-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0015_alter_bookmodel_availiblity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='availiblity',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='total_books',
            field=models.IntegerField(null=True),
        ),
    ]
