# Generated by Django 3.2.8 on 2021-10-07 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryApp', '0016_auto_20211006_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_books', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='total_books',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
