# Generated by Django 3.2.8 on 2021-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0017_auto_20211007_0603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Totalbook',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='quantity',
            field=models.IntegerField(default=False),
        ),
    ]
