# Generated by Django 3.2.8 on 2021-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0018_auto_20211007_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
